# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OCR_PRA.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("QWidget{\n"
"    color: rgb(221, 221, 221);\n"
"    font: 10pt \"HarmonyOS Sans SC\";\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"/*Tooltip */\n"
"QToolTip {\n"
"    color: rgb(221,221,221);\n"
"    background-color: rgba(33, 37, 43);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    background-image: none;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 2px solid rgb(111, 168, 220);\n"
"    text-align: left;\n"
"    padding-left: 5px;\n"
"    margin: 0px;\n"
"}\n"
"/*  QDockWidget  */\n"
"QDockWidget {\n"
"  color: rgb(221, 221, 221);\n"
"  font: 10pt \"HarmonyOS Sans SC\";\n"
"  background-color: rgb(40, 44, 52);\n"
"  text-transform: uppercase;\n"
"  border: 2px solid rgb(64, 71, 88);\n"
"  border-radius: 5px;\n"
"  titlebar-close-icon:  url(:/icons/images/icons/close.png);\n"
"  titlebar-normal-icon: url(:/icons/images/icons/icon_restore.png);\n"
"}\n"
"QDockWidget>QWidget{\n"
"  border: 2px solid rgb(64, 71, 88);\n"
"  border-radius: 5px;\n"
"  margin-top:5px;\n"
"  margin-left:8px;\n"
"  margin-right:8px;\n"
"  margin-bottom:9px;\n"
"}\n"
"QDockWidget::title {\n"
"  background-color:rgb(33, 37, 43);\n"
"  text-align: left;\n"
"  padding: 5px;\n"
"  padding-left: 3px;\n"
"  margin-top:8px;\n"
"  margin-left:8px;\n"
"  margin-right:8px;\n"
"  border: 2px solid rgb(64, 71, 88);\n"
"  border-radius: 5px;\n"
"}\n"
"QDockWidget::float-button,QDockWidget::close-button\n"
" {\n"
"    border: 1px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    width: 20px; \n"
"    subcontrol-position: center right;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"    top: 8px; \n"
"    left: 0px; \n"
"    bottom: 0px;\n"
"    right:14px;\n"
"}\n"
"\n"
"QDockWidget::float-button:hover {\n"
"  background-color: rgb(57, 65, 80);\n"
"  border: 1px solid rgb(61, 70, 86);\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QDockWidget::close-button:hover {\n"
"  background-color: rgb(57, 65, 80);\n"
"  border: 1px solid rgb(61, 70, 86);\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QDockWidget::float-button:pressed {\n"
"  background-color: rgb(35, 40, 49);\n"
"  border: 1px solid rgb(43, 50, 61);\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed {\n"
"  background-color: rgb(35, 40, 49);\n"
"  border: 1px solid rgb(43, 50, 61);\n"
"  border-radius: 5px;\n"
"}\n"
"QDockWidget::float-button:disabled,\n"
"QDockWidget::close-button:disabled {\n"
"    border: 1px solid rgb(43, 50, 61);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(43, 50, 61);\n"
"}\n"
"QDockWidget:disabled {\n"
"    color:rgb(120,120,120);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"    background-color: rgb(43, 50, 61);\n"
"}\n"
"\n"
"/*  QScrollBar  */\n"
"QScrollBar:horizontal {\n"
"  border: 1px solid  rgb(23, 27, 33);\n"
"  border-radius: 5px;\n"
"  background-color: rgb(23, 27, 33);\n"
"  height: 12px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"  border: 1px solid  rgb(23, 27, 33);\n"
"  border-radius: 5px;\n"
"  background-color: rgb(23, 27, 33);\n"
"  width: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
"  border: 1 solid  rgb(71, 128, 180);\n"
"  border-radius: 5px;\n"
"  background-color: rgb(71, 128, 180);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"  min-width: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"  min-height: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover,\n"
"QScrollBar::handle:horizontal:hover {\n"
"  background-color: rgb(111, 168, 220);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"  border: 0;\n"
"  background: transparent;\n"
"  width: 0px;\n"
"  height: 0px;\n"
"}\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:vertical,\n"
"QScrollBar::sub-page:horizontal\n"
"{\n"
"    background:transparent;\n"
"}\n"
"\n"
"/*  QSlider  */\n"
"QSlider:horizontal {\n"
"  min-height: 24px;\n"
"  max-height: 24px;\n"
"}\n"
"\n"
"QSlider:vertical {\n"
"  min-width: 24px;\n"
"  max-width: 24px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"  height: 4px;\n"
"  background: rgb(33, 37, 43);\n"
"  margin: 0 10px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"  width: 4px;\n"
"  background: rgb(33, 37, 43);\n"
"  border-radius: 24px;\n"
"  margin: 10px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"  image: url(:/icons/images/icons/circle.svg);\n"
"  width: 20px;\n"
"  height: 20px;\n"
"  margin: -20px -10px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"  image: url(:/icons/images/icons/circle.svg);\n"
"  border-radius: 20px;\n"
"  width: 20px;\n"
"  height: 20px;\n"
"  margin: -10px -20px;\n"
"}\n"
"\n"
"QSlider::add-page {\n"
"background: rgb(33, 37, 43);\n"
"}\n"
"\n"
"QSlider::sub-page {\n"
"background: rgb(111, 168, 220);\n"
"}\n"
"\n"
"/*  Spin buttons  */\n"
"QDateTimeEdit,\n"
"QDoubleSpinBox,\n"
"QSpinBox {\n"
"     background-color: rgb(33, 37, 43);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(111, 168, 220);\n"
"}\n"
"QDateTimeEdit:hover,\n"
"QDoubleSpinBox:hover,\n"
"QSpinBox:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QDateTimeEdit:focus,\n"
"QDoubleSpinBox:focus,\n"
"QSpinBox:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"QDateTimeEdit:disabled,\n"
"QDoubleSpinBox:disabled,\n"
"QSpinBox:disabled {\n"
"     color:rgb(120,120,120);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"    background-color: rgb(43, 50, 61);\n"
"}\n"
"\n"
"QDateTimeEdit::up-button,\n"
"QDoubleSpinBox::up-button,\n"
"QSpinBox::up-button {\n"
"  subcontrol-origin: border;\n"
"  subcontrol-position: top right;\n"
"  width: 20px;\n"
"  image: url(:/icons/images/icons/cil-arrow-top.png);\n"
"  border-width: 0px;\n"
"  margin-right: 5px;\n"
"  margin-top: 5px;\n"
"}\n"
"\n"
"QDateTimeEdit::up-button:disabled,\n"
"QDoubleSpinBox::up-button:disabled,\n"
"QSpinBox::up-button:disabled {\n"
"     image: url(:/icons/images/icons/cil-arrow-top.png);\n"
"     color:rgb(120,120,120);\n"
"}\n"
"\n"
"QDateTimeEdit::down-button,\n"
"QDoubleSpinBox::down-button,\n"
"QSpinBox::down-button {\n"
"  subcontrol-origin: border;\n"
"  subcontrol-position: bottom right;\n"
"  width: 20px;\n"
"  image: url(:/icons/images/icons/cil-arrow-bottom.png);\n"
"  border-width: 0px;\n"
"  border-top-width: 0;\n"
"  margin-right: 5px;\n"
"  margin-bottom: 5px;\n"
"}\n"
"\n"
"QDateTimeEdit::down-button:disabled,\n"
"QDoubleSpinBox::down-button:disabled,\n"
"QSpinBox::down-button:disabled {\n"
"  image: url(:/icons/images/icons/cil-arrow-bottom.png);\n"
"}\n"
"\n"
"/*  QComboBox  */\n"
"QComboBox {\n"
"  color:  rgb(221, 221, 221);\n"
"  background-color: rgb(33, 37, 43);\n"
"  border-radius: 5px;\n"
"  border: 2px solid rgb(33, 37, 43);\n"
"  selection-color: rgb(255, 255, 255);\n"
"  selection-background-color: rgb(111, 168, 220);\n"
"  border-top-left-radius: 4px;\n"
"  border-top-right-radius: 4px;\n"
"  padding-left: 10px;\n"
"  height: 30px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"QComboBox:disabled {\n"
"  color:rgb(120,120,120);\n"
"  border: 2px solid rgb(43, 50, 61);\n"
"  background-color: rgb(43, 50, 61);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"  border: none;\n"
"  width: 20px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"  image: url(:/icons/images/icons/cil-arrow-bottom.png);\n"
"  margin-right: 12px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  background-color: rgb(33, 37, 43);\n"
"  border: 2px solid rgb(64, 71, 88);\n"
"  border-radius: 0px;\n"
"}\n"
"QComboBox::indicator:checked {\n"
"  image: url(:/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"\n"
"QComboBox::item {\n"
"  height: 25px;\n"
"  border: 5px solid transparent;\n"
"  padding-left:0px;\n"
"  color:rgb(221, 221, 221);\n"
"}\n"
"QComboBox::item:selected {\n"
"  color:  rgb(221, 221, 221);\n"
"  background-color: rgb(111, 168, 220);\n"
"  border-radius: 0px;\n"
"}\n"
"\n"
"/*Label*/\n"
"QLabel {\n"
"    color: rgb(221, 221, 221);\n"
"    padding-left: 5px;\n"
"    padding-right: 2px;\n"
"    border-radius: 5px;    \n"
"    background-color: transparent;\n"
"}\n"
"QLabel:disabled {\n"
"    color:rgb(120,120,120);\n"
"    background-color: transparent;\n"
"}\n"
"/*Button */\n"
"QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"QPushButton:disabled {\n"
"    color:rgb(120,120,120);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(43, 50, 61);\n"
"}\n"
"\n"
"/*LineEdit */\n"
"QLineEdit {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(111, 168, 220);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"QLineEdit:disabled {\n"
"    color:rgb(120,120,120);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"    background-color: rgb(43, 50, 61);\n"
"}\n"
"/* RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"QRadioButton:disabled {\n"
"    color:rgb(120,120,120);\n"
"    border: 3px solid rgb(43, 50, 61);\n"
"    background-color: rgb(43, 50, 61);\n"
"}\n"
"/*CheckBox */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"QCheckBox:disabled {\n"
"    color:rgb(120,120,120);\n"
"    border: 3px solid rgb(43, 50, 61);\n"
"    background-color: rgb(43, 50, 61);\n"
"}\n"
"/*  QTabBar  */\n"
"QTabWidget{\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"QTabBar{\n"
"  text-transform: uppercase;\n"
"  font-weight: bold;\n"
"  background-color: rgb(40, 44, 52);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"  max-width:150px;\n"
"  min-width:150px;\n"
"  max-height:30px;\n"
"  min-height:30px;\n"
"  border:0px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom,QTabBar::tab:top{\n"
"  padding: 3px;\n"
"  height: 30px;\n"
"}\n"
"\n"
"QTabBar::tab:left,QTabBar::tab:right{\n"
"  padding: 3px;\n"
"  width: 30px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected,\n"
"QTabBar::tab:top:hover {\n"
"  color: rgb(109, 158, 235);\n"
"  border-bottom: 3px solid rgb(109, 158, 235);\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected,\n"
"QTabBar::tab:bottom:hover {\n"
"  padding: 0px;\n"
"  color:rgb(109, 158, 235);\n"
"  border-top: 3px solid rgb(109, 158, 235);\n"
"}\n"
"\n"
"QTabBar::tab:right:selected,\n"
"QTabBar::tab:right:hover {\n"
"  color: rgb(109, 158, 235);\n"
"  border-left: 3px solid rgb(109, 158, 235);\n"
"}\n"
"\n"
"QTabBar::tab:left:selected,\n"
"QTabBar::tab:left:hover {\n"
"  color: rgb(109, 158, 235);\n"
"  border-right: 3px solid rgb(109, 158, 235);\n"
"}\n"
"\n"
"QTabBar::close-button {\n"
"  image: url(:/icons/images/icons/close.svg);\n"
"  background-color:  rgb(40, 44, 52);\n"
"  border-radius: 10px; \n"
"}\n"
"\n"
"QTabBar::close-button:hover {\n"
"    background-color: rgb(253, 84, 63);\n"
"}\n"
"QTabBar::close-button:pressed {\n"
"    background-color: rgb(196, 58, 43);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 400))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setStyleSheet("/*  QGroupBox  */\n"
"QGroupBox \n"
"{\n"
"  background-color: rgb(40, 44, 52);\n"
"  border: 2px solid rgb(64, 71, 88);\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QGroupBox.fill_background\n"
"{\n"
"  background-color: rgb(40, 44, 52);\n"
"  border: 2px solid rgb(64, 71, 88);\n"
"  border-radius: 5px;\n"
"}\n"
"QGroupBox {\n"
"  padding: 5px;\n"
"  padding-top: 20px;\n"
"  text-transform: uppercase;\n"
"  font-size: 10;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"  color: rgb(221,221,221);\n"
"  subcontrol-origin: margin;\n"
"  subcontrol-position: top center;\n"
"  padding-top: 8px;\n"
"  padding-bottom: 5px;\n"
"  background-color:  rgb(40, 44, 52);\n"
"  background-color: transparent;\n"
"  height: 24px;\n"
"}")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.borswer_layout = QtWidgets.QVBoxLayout()
        self.borswer_layout.setObjectName("borswer_layout")
        self.verticalLayout_7.addLayout(self.borswer_layout)
        self.verticalLayout_10.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.instruct_dockwidget = QtWidgets.QDockWidget(MainWindow)
        self.instruct_dockwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instruct_dockwidget.sizePolicy().hasHeightForWidth())
        self.instruct_dockwidget.setSizePolicy(sizePolicy)
        self.instruct_dockwidget.setMinimumSize(QtCore.QSize(227, 475))
        self.instruct_dockwidget.setMaximumSize(QtCore.QSize(524287, 524287))
        self.instruct_dockwidget.setStyleSheet("")
        self.instruct_dockwidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.instruct_dockwidget.setObjectName("instruct_dockwidget")
        self.instruct_dockWidgetContents = QtWidgets.QWidget()
        self.instruct_dockWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.instruct_dockWidgetContents.setObjectName("instruct_dockWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.instruct_dockWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(8, 5, 8, 9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.open_instruct = QtWidgets.QPushButton(self.instruct_dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_instruct.sizePolicy().hasHeightForWidth())
        self.open_instruct.setSizePolicy(sizePolicy)
        self.open_instruct.setMinimumSize(QtCore.QSize(25, 25))
        self.open_instruct.setMaximumSize(QtCore.QSize(25, 25))
        self.open_instruct.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/open_file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_instruct.setIcon(icon)
        self.open_instruct.setIconSize(QtCore.QSize(20, 20))
        self.open_instruct.setObjectName("open_instruct")
        self.verticalLayout.addWidget(self.open_instruct)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.save_instruct = QtWidgets.QPushButton(self.instruct_dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_instruct.sizePolicy().hasHeightForWidth())
        self.save_instruct.setSizePolicy(sizePolicy)
        self.save_instruct.setMinimumSize(QtCore.QSize(25, 25))
        self.save_instruct.setMaximumSize(QtCore.QSize(25, 25))
        self.save_instruct.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_instruct.setIcon(icon1)
        self.save_instruct.setObjectName("save_instruct")
        self.verticalLayout.addWidget(self.save_instruct)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.clear_instruct = QtWidgets.QPushButton(self.instruct_dockWidgetContents)
        self.clear_instruct.setMinimumSize(QtCore.QSize(25, 25))
        self.clear_instruct.setMaximumSize(QtCore.QSize(25, 25))
        self.clear_instruct.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/clear_all.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_instruct.setIcon(icon2)
        self.clear_instruct.setIconSize(QtCore.QSize(20, 20))
        self.clear_instruct.setObjectName("clear_instruct")
        self.verticalLayout.addWidget(self.clear_instruct)
        self.line_3 = QtWidgets.QFrame(self.instruct_dockWidgetContents)
        self.line_3.setMinimumSize(QtCore.QSize(25, 0))
        self.line_3.setMaximumSize(QtCore.QSize(25, 16777215))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.up_instruct = QtWidgets.QPushButton(self.instruct_dockWidgetContents)
        self.up_instruct.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.up_instruct.sizePolicy().hasHeightForWidth())
        self.up_instruct.setSizePolicy(sizePolicy)
        self.up_instruct.setMinimumSize(QtCore.QSize(25, 25))
        self.up_instruct.setMaximumSize(QtCore.QSize(25, 25))
        self.up_instruct.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/icons/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.up_instruct.setIcon(icon3)
        self.up_instruct.setIconSize(QtCore.QSize(20, 20))
        self.up_instruct.setObjectName("up_instruct")
        self.verticalLayout.addWidget(self.up_instruct)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.down_instruct = QtWidgets.QPushButton(self.instruct_dockWidgetContents)
        self.down_instruct.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.down_instruct.sizePolicy().hasHeightForWidth())
        self.down_instruct.setSizePolicy(sizePolicy)
        self.down_instruct.setMinimumSize(QtCore.QSize(25, 25))
        self.down_instruct.setMaximumSize(QtCore.QSize(25, 25))
        self.down_instruct.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/icons/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.down_instruct.setIcon(icon4)
        self.down_instruct.setIconSize(QtCore.QSize(20, 20))
        self.down_instruct.setObjectName("down_instruct")
        self.verticalLayout.addWidget(self.down_instruct)
        self.line_4 = QtWidgets.QFrame(self.instruct_dockWidgetContents)
        self.line_4.setMinimumSize(QtCore.QSize(25, 0))
        self.line_4.setMaximumSize(QtCore.QSize(25, 16777215))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.show_instruct = QtWidgets.QPushButton(self.instruct_dockWidgetContents)
        self.show_instruct.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_instruct.sizePolicy().hasHeightForWidth())
        self.show_instruct.setSizePolicy(sizePolicy)
        self.show_instruct.setMinimumSize(QtCore.QSize(25, 25))
        self.show_instruct.setMaximumSize(QtCore.QSize(25, 25))
        self.show_instruct.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/icons/eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.show_instruct.setIcon(icon5)
        self.show_instruct.setObjectName("show_instruct")
        self.verticalLayout.addWidget(self.show_instruct)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.add_instruct = QtWidgets.QPushButton(self.instruct_dockWidgetContents)
        self.add_instruct.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_instruct.sizePolicy().hasHeightForWidth())
        self.add_instruct.setSizePolicy(sizePolicy)
        self.add_instruct.setMinimumSize(QtCore.QSize(25, 25))
        self.add_instruct.setMaximumSize(QtCore.QSize(25, 25))
        self.add_instruct.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_instruct.setIcon(icon6)
        self.add_instruct.setObjectName("add_instruct")
        self.verticalLayout.addWidget(self.add_instruct)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem4)
        self.edit_instruct = QtWidgets.QPushButton(self.instruct_dockWidgetContents)
        self.edit_instruct.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_instruct.sizePolicy().hasHeightForWidth())
        self.edit_instruct.setSizePolicy(sizePolicy)
        self.edit_instruct.setMinimumSize(QtCore.QSize(25, 25))
        self.edit_instruct.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edit_instruct.setFont(font)
        self.edit_instruct.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/icons/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_instruct.setIcon(icon7)
        self.edit_instruct.setShortcut("")
        self.edit_instruct.setFlat(False)
        self.edit_instruct.setObjectName("edit_instruct")
        self.verticalLayout.addWidget(self.edit_instruct)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem5)
        self.delete_instruct = QtWidgets.QPushButton(self.instruct_dockWidgetContents)
        self.delete_instruct.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_instruct.sizePolicy().hasHeightForWidth())
        self.delete_instruct.setSizePolicy(sizePolicy)
        self.delete_instruct.setMinimumSize(QtCore.QSize(25, 25))
        self.delete_instruct.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.delete_instruct.setFont(font)
        self.delete_instruct.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/images/icons/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_instruct.setIcon(icon8)
        self.delete_instruct.setObjectName("delete_instruct")
        self.verticalLayout.addWidget(self.delete_instruct)
        self.line = QtWidgets.QFrame(self.instruct_dockWidgetContents)
        self.line.setMinimumSize(QtCore.QSize(25, 0))
        self.line.setMaximumSize(QtCore.QSize(25, 16777215))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.instruct_list = QtWidgets.QTreeWidget(self.instruct_dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instruct_list.sizePolicy().hasHeightForWidth())
        self.instruct_list.setSizePolicy(sizePolicy)
        self.instruct_list.setMinimumSize(QtCore.QSize(100, 300))
        self.instruct_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.instruct_list.setFont(font)
        self.instruct_list.setFocusPolicy(QtCore.Qt.NoFocus)
        self.instruct_list.setStyleSheet("QTreeView {\n"
"  padding:  5px;\n"
"  background-color: rgb(40, 44, 52);\n"
"  border:1px solid rgb(64, 71, 88);\n"
"  height: 30px;\n"
"  border-radius: 4px;\n"
"  margin: 0;\n"
"}\n"
"QTreeView QHeaderView::section {\n"
"  background-color: rgb(33, 37, 43);\n"
"  color: rgb(221,221,221);\n"
"  padding: 5px;\n"
"  border-radius: 4px;\n"
"  border: 1px solid rgb(64, 71, 88);\n"
"}\n"
"QTreeView::item {\n"
"  min-height: 30px;\n"
"  color: rgb(221, 221, 221);\n"
"  selection-color: rgb(221, 221, 221); /* For Windows */\n"
"}\n"
"/*  Items Selection */\n"
"QTreeView::item:selected {\n"
"  /*\n"
"  background-image: url(:/icons/images/icons/cil-caret-right.png);\n"
"  background-repeat: no-repaet;\n"
"  background-position:center left;\n"
"*/\n"
"  padding:  0px;\n"
"  background-color: rgb(71, 128, 180);\n"
"  selection-background-color: rgb(71, 128, 180);\n"
"  color:rgb(221, 221, 221);\n"
"  selection-color:rgb(221, 221, 221); /* For Windows */\n"
"  border-radius: 4px;\n"
"  border:1px solid rgb(33, 37, 43);\n"
"}\n"
"\n"
"QTreeView::item:selected:focus {\n"
"  background-color: rgb(111, 168, 220);\n"
"  selection-background-color: rgb(111, 168, 220);\n"
"  color: rgb(255, 255, 255);\n"
"  selection-color: rgb(255, 255, 255); /* For Windows */\n"
"}\n"
"\n"
"QTreeView::item:disabled {\n"
"  color: rgb(120,120,120);\n"
"  selection-color: rgb(120,120,120);\n"
"  background-color: rgb(43, 50, 61);\n"
"  selection-background-color: rgb(43, 50, 61);\n"
"}\n"
"QTreeView::branch{\n"
"  background-color: rgb(40, 44, 52);\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children:has-siblings,\n"
"QTreeView::branch:closed:has-children:!has-siblings {\n"
"  image: url(:/icons/images/icons/cil-caret-right.png);\n"
"  padding: 5px;\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings {\n"
"  image: url(:/icons/images/icons/cil-caret-bottom.png);\n"
"  padding: 5px;\n"
"}\n"
"\n"
"QTreeView QLineEdit {\n"
"  color: rgb(221, 221, 221);\n"
"  background-color: rgb(40, 44, 52);\n"
"  border: 1px solid unset;\n"
"  border-radius: unset;\n"
"  padding: unset;\n"
"  padding-left: unset;\n"
"  height: unset;\n"
"  border-width: unset;\n"
"  border-top-left-radius: unset;\n"
"  border-top-right-radius: unset;\n"
"}")
        self.instruct_list.setObjectName("instruct_list")
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.instruct_list.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.instruct_list)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.instruct_list)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        item_0.setFont(0, font)
        self.horizontalLayout_2.addWidget(self.instruct_list)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.instruct_dockwidget.setWidget(self.instruct_dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.instruct_dockwidget)
        self.edit_dockwidget = QtWidgets.QDockWidget(MainWindow)
        self.edit_dockwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_dockwidget.sizePolicy().hasHeightForWidth())
        self.edit_dockwidget.setSizePolicy(sizePolicy)
        self.edit_dockwidget.setMinimumSize(QtCore.QSize(809, 288))
        self.edit_dockwidget.setMaximumSize(QtCore.QSize(524287, 524287))
        self.edit_dockwidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.edit_dockwidget.setObjectName("edit_dockwidget")
        self.edit_dockWidgetContents = QtWidgets.QWidget()
        self.edit_dockWidgetContents.setEnabled(True)
        self.edit_dockWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.edit_dockWidgetContents.setObjectName("edit_dockWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.edit_dockWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(8, 5, 8, 9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.type_label = QtWidgets.QLabel(self.edit_dockWidgetContents)
        self.type_label.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.type_label.sizePolicy().hasHeightForWidth())
        self.type_label.setSizePolicy(sizePolicy)
        self.type_label.setMinimumSize(QtCore.QSize(0, 30))
        self.type_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.type_label.setFont(font)
        self.type_label.setAlignment(QtCore.Qt.AlignCenter)
        self.type_label.setObjectName("type_label")
        self.horizontalLayout_5.addWidget(self.type_label)
        self.type = QtWidgets.QComboBox(self.edit_dockWidgetContents)
        self.type.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.type.sizePolicy().hasHeightForWidth())
        self.type.setSizePolicy(sizePolicy)
        self.type.setMinimumSize(QtCore.QSize(120, 30))
        self.type.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.type.setFont(font)
        self.type.setEditable(False)
        self.type.setFrame(True)
        self.type.setObjectName("type")
        self.type.addItem("")
        self.type.addItem("")
        self.type.addItem("")
        self.type.addItem("")
        self.type.addItem("")
        self.type.addItem("")
        self.horizontalLayout_5.addWidget(self.type)
        self.xpath_label = QtWidgets.QLabel(self.edit_dockWidgetContents)
        self.xpath_label.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xpath_label.sizePolicy().hasHeightForWidth())
        self.xpath_label.setSizePolicy(sizePolicy)
        self.xpath_label.setMinimumSize(QtCore.QSize(0, 30))
        self.xpath_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.xpath_label.setFont(font)
        self.xpath_label.setObjectName("xpath_label")
        self.horizontalLayout_5.addWidget(self.xpath_label)
        self.xpath = QtWidgets.QLineEdit(self.edit_dockWidgetContents)
        self.xpath.setEnabled(False)
        self.xpath.setMinimumSize(QtCore.QSize(0, 30))
        self.xpath.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xpath.setObjectName("xpath")
        self.horizontalLayout_5.addWidget(self.xpath)
        self.extra_label = QtWidgets.QLabel(self.edit_dockWidgetContents)
        self.extra_label.setEnabled(False)
        self.extra_label.setObjectName("extra_label")
        self.horizontalLayout_5.addWidget(self.extra_label)
        self.extra_input = QtWidgets.QLineEdit(self.edit_dockWidgetContents)
        self.extra_input.setEnabled(False)
        self.extra_input.setMinimumSize(QtCore.QSize(0, 30))
        self.extra_input.setObjectName("extra_input")
        self.horizontalLayout_5.addWidget(self.extra_input)
        self.index_label = QtWidgets.QLabel(self.edit_dockWidgetContents)
        self.index_label.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.index_label.sizePolicy().hasHeightForWidth())
        self.index_label.setSizePolicy(sizePolicy)
        self.index_label.setMinimumSize(QtCore.QSize(0, 30))
        self.index_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.index_label.setFont(font)
        self.index_label.setObjectName("index_label")
        self.horizontalLayout_5.addWidget(self.index_label)
        self.index = QtWidgets.QSpinBox(self.edit_dockWidgetContents)
        self.index.setEnabled(False)
        self.index.setMinimumSize(QtCore.QSize(80, 30))
        self.index.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.index.setFont(font)
        self.index.setMaximum(200)
        self.index.setObjectName("index")
        self.horizontalLayout_5.addWidget(self.index)
        self.submit = QtWidgets.QPushButton(self.edit_dockWidgetContents)
        self.submit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submit.sizePolicy().hasHeightForWidth())
        self.submit.setSizePolicy(sizePolicy)
        self.submit.setMinimumSize(QtCore.QSize(80, 30))
        self.submit.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.horizontalLayout_5.addWidget(self.submit)
        self.clear = QtWidgets.QPushButton(self.edit_dockWidgetContents)
        self.clear.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear.sizePolicy().hasHeightForWidth())
        self.clear.setSizePolicy(sizePolicy)
        self.clear.setMinimumSize(QtCore.QSize(80, 30))
        self.clear.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.clear.setFont(font)
        self.clear.setObjectName("clear")
        self.horizontalLayout_5.addWidget(self.clear)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.line_2 = QtWidgets.QFrame(self.edit_dockWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.table_editor = QtWidgets.QWidget(self.edit_dockWidgetContents)
        self.table_editor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_editor.sizePolicy().hasHeightForWidth())
        self.table_editor.setSizePolicy(sizePolicy)
        self.table_editor.setObjectName("table_editor")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.table_editor)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.delete_row = QtWidgets.QPushButton(self.table_editor)
        self.delete_row.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_row.sizePolicy().hasHeightForWidth())
        self.delete_row.setSizePolicy(sizePolicy)
        self.delete_row.setMinimumSize(QtCore.QSize(85, 0))
        self.delete_row.setMaximumSize(QtCore.QSize(85, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.delete_row.setFont(font)
        self.delete_row.setObjectName("delete_row")
        self.horizontalLayout_4.addWidget(self.delete_row)
        self.add_row = QtWidgets.QPushButton(self.table_editor)
        self.add_row.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_row.sizePolicy().hasHeightForWidth())
        self.add_row.setSizePolicy(sizePolicy)
        self.add_row.setMinimumSize(QtCore.QSize(85, 0))
        self.add_row.setMaximumSize(QtCore.QSize(85, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.add_row.setFont(font)
        self.add_row.setObjectName("add_row")
        self.horizontalLayout_4.addWidget(self.add_row)
        spacerItem8 = QtWidgets.QSpacerItem(40, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.xpath_table = QtWidgets.QTableWidget(self.table_editor)
        self.xpath_table.setEnabled(False)
        self.xpath_table.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.xpath_table.setFont(font)
        self.xpath_table.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.xpath_table.setStyleSheet("QTableView {\n"
"  font: 10t \"HarmonyOS Sans SC\";\n"
"  background-color: rgb(40, 44, 52);\n"
"  border: 1px solid rgb(64, 71, 88);\n"
"  border-radius: 4px;\n"
"  selection-background-color: rgb(71, 128, 180);\n"
"  /*两行交替的颜色，第二行*/\n"
"  alternate-background-color: rgb(43, 47, 53);\n"
"}\n"
"\n"
"QTableView:focus {\n"
"  selection-background-color: rgb(111, 168, 220);\n"
"}\n"
"\n"
"QTableView::item {\n"
"  font: 8t \"HarmonyOS Sans SC\";\n"
"  padding: 0px;\n"
"  min-height: 32px;\n"
"  color: rgb(221, 221, 221);\n"
"  selection-color: rgb(221, 221, 221); /* For Windows */\n"
"}\n"
"/*  Items Selection */\n"
"QTableView::item:selected {\n"
"  background-color: rgb(71, 128, 180);\n"
"  selection-background-color: rgb(71, 128, 180);\n"
"  color:rgb(221, 221, 221);\n"
"  selection-color:rgb(221, 221, 221); /* For Windows */\n"
"}\n"
"\n"
"QTableView::item:selected:focus {\n"
"  background-color: rgb(111, 168, 220);\n"
"  selection-background-color: rgb(111, 168, 220);\n"
"  color: rgb(255, 255, 255);\n"
"  selection-color: rgb(255, 255, 255); /* For Windows */\n"
"}\n"
"QTableView::item:disabled {\n"
"  color: rgb(120,120,120);\n"
"  selection-color: rgb(120,120,120);\n"
"  background-color: rgb(43, 50, 61);\n"
"  selection-background-color: rgb(43, 50, 61);\n"
"}\n"
"/*  QTableView  */\n"
"\n"
"QTableCornerButton::section {\n"
"  background-color: rgb(33, 37, 43);\n"
"  border-radius: 2px;\n"
"  border-right: 1px solid;\n"
"  border-bottom: 1px solid;\n"
"  border-color: rgb(64, 71, 88);\n"
"}\n"
"QTableCornerButton::section:disabled {\n"
"  background-color:  rgb(43, 50, 61);\n"
"  border-radius: 2px;\n"
"  border-right: 1px solid;\n"
"  border-bottom: 1px solid;\n"
"  border-color: rgb(64, 71, 88);\n"
"}\n"
"\n"
"QHeaderView {\n"
"  border: none;\n"
"}\n"
"\n"
"QHeaderView::section:disabled {\n"
"  color: rgb(120, 120, 120);\n"
"  text-transform: uppercase;\n"
"  background-color: rgb(43, 50, 61);\n"
"  border-radius: 2px;\n"
"  border-right: 1px solid;\n"
"  border-bottom: 1px solid;\n"
"  border-color:rgb(64, 71, 88);\n"
"}\n"
"QHeaderView::section {\n"
"  color: rgb(221, 221, 221);\n"
"  text-transform: uppercase;\n"
"  background-color: rgb(33, 37, 43);\n"
"  border-radius: 2px;\n"
"  border-right: 1px solid;\n"
"  border-bottom: 1px solid;\n"
"  border-color:rgb(64, 71, 88);\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"  padding: 10 0 10 0;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"  padding: 0 10 0 10;\n"
"}\n"
"QTableView QLineEdit {\n"
"  color: rgb(221, 221, 221);\n"
"  background-color: rgb(33, 37, 43);\n"
"  border: 1px solid rgb(111, 168, 220);\n"
"  border-radius: unset;\n"
"  padding: unset;\n"
"  padding-left: unset;\n"
"  height: unset;\n"
"  border-width: unset;\n"
"  border-top-left-radius: unset;\n"
"  border-top-right-radius: unset;\n"
"}\n"
"QTableView QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QTableView QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.xpath_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.xpath_table.setAlternatingRowColors(True)
        self.xpath_table.setShowGrid(True)
        self.xpath_table.setObjectName("xpath_table")
        self.xpath_table.setColumnCount(2)
        self.xpath_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.xpath_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.xpath_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.xpath_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.xpath_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.xpath_table.setItem(0, 1, item)
        self.xpath_table.horizontalHeader().setCascadingSectionResizes(False)
        self.xpath_table.horizontalHeader().setDefaultSectionSize(100)
        self.xpath_table.horizontalHeader().setMinimumSectionSize(40)
        self.xpath_table.horizontalHeader().setStretchLastSection(True)
        self.xpath_table.verticalHeader().setCascadingSectionResizes(False)
        self.xpath_table.verticalHeader().setDefaultSectionSize(30)
        self.xpath_table.verticalHeader().setMinimumSectionSize(25)
        self.xpath_table.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_9.addWidget(self.xpath_table)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_3.addWidget(self.table_editor)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.edit_dockwidget.setWidget(self.edit_dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.edit_dockwidget)

        self.retranslateUi(MainWindow)
        self.type.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "浏览器"))
        self.instruct_dockwidget.setWindowTitle(_translate("MainWindow", "指令列表"))
        self.open_instruct.setToolTip(_translate("MainWindow", "打开文件"))
        self.save_instruct.setToolTip(_translate("MainWindow", "保存文件"))
        self.clear_instruct.setToolTip(_translate("MainWindow", "清除指令列表"))
        self.up_instruct.setToolTip(_translate("MainWindow", "上移指令"))
        self.down_instruct.setToolTip(_translate("MainWindow", "下移指令"))
        self.show_instruct.setToolTip(_translate("MainWindow", "显示XPath"))
        self.add_instruct.setToolTip(_translate("MainWindow", "新建指令"))
        self.edit_instruct.setToolTip(_translate("MainWindow", "编辑指令"))
        self.delete_instruct.setToolTip(_translate("MainWindow", "删除指令"))
        self.instruct_list.headerItem().setText(0, _translate("MainWindow", "步骤"))
        __sortingEnabled = self.instruct_list.isSortingEnabled()
        self.instruct_list.setSortingEnabled(False)
        self.instruct_list.topLevelItem(0).setText(0, _translate("MainWindow", "登录"))
        self.instruct_list.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "打开登录网址"))
        self.instruct_list.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "用户名"))
        self.instruct_list.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "密码"))
        self.instruct_list.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "验证码"))
        self.instruct_list.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "验证码图片"))
        self.instruct_list.topLevelItem(0).child(5).setText(0, _translate("MainWindow", "登录按钮"))
        self.instruct_list.topLevelItem(1).setText(0, _translate("MainWindow", "操作"))
        self.instruct_list.setSortingEnabled(__sortingEnabled)
        self.edit_dockwidget.setWindowTitle(_translate("MainWindow", "登录"))
        self.type_label.setText(_translate("MainWindow", "操作"))
        self.type.setItemText(0, _translate("MainWindow", "打开网址"))
        self.type.setItemText(1, _translate("MainWindow", "点击"))
        self.type.setItemText(2, _translate("MainWindow", "输入文本"))
        self.type.setItemText(3, _translate("MainWindow", "切换"))
        self.type.setItemText(4, _translate("MainWindow", "复选"))
        self.type.setItemText(5, _translate("MainWindow", "获取元素"))
        self.xpath_label.setText(_translate("MainWindow", "定位方式"))
        self.extra_label.setText(_translate("MainWindow", "用户名"))
        self.index_label.setText(_translate("MainWindow", "数据索引"))
        self.submit.setText(_translate("MainWindow", "提交"))
        self.clear.setText(_translate("MainWindow", "清除"))
        self.delete_row.setText(_translate("MainWindow", "删除行"))
        self.add_row.setText(_translate("MainWindow", "新增行"))
        item = self.xpath_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.xpath_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "名称"))
        item = self.xpath_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "XPath"))
        __sortingEnabled = self.xpath_table.isSortingEnabled()
        self.xpath_table.setSortingEnabled(False)
        self.xpath_table.setSortingEnabled(__sortingEnabled)
import lib.resources_rc
