# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(873, 944)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("QWidget{\n"
"    color: rgb(221, 221, 221);\n"
"    font: 10pt \"HarmonyOS Sans SC\";\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"/*Tooltip */\n"
"QToolTip {\n"
"    color: rgb(221,221,221);\n"
"    background-color: rgba(33, 37, 43);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    background-image: none;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 2px solid rgb(111, 168, 220);\n"
"    text-align: left;\n"
"    padding-left: 5px;\n"
"    margin: 0px;\n"
"}\n"
"/*  QDockWidget  */\n"
"QDockWidget {\n"
"  color: rgb(221, 221, 221);\n"
"  font: 10pt \"HarmonyOS Sans SC\";\n"
"  background-color: rgb(40, 44, 52);\n"
"  text-transform: uppercase;\n"
"  border: 2px solid rgb(64, 71, 88);\n"
"  border-radius: 5px;\n"
"  titlebar-close-icon:  url(:/icons/images/icons/close.png);\n"
"  titlebar-normal-icon: url(:/icons/images/icons/icon_restore.png);\n"
"}\n"
"QDockWidget>QWidget{\n"
"  border: 2px solid rgb(64, 71, 88);\n"
"  border-radius: 5px;\n"
"  margin-top:5px;\n"
"  margin-left:8px;\n"
"  margin-right:8px;\n"
"  margin-bottom:9px;\n"
"}\n"
"QDockWidget::title {\n"
"  background-color:rgb(33, 37, 43);\n"
"  text-align: left;\n"
"  padding: 5px;\n"
"  padding-left: 3px;\n"
"  margin-top:8px;\n"
"  margin-left:8px;\n"
"  margin-right:8px;\n"
"  border: 2px solid rgb(64, 71, 88);\n"
"  border-radius: 5px;\n"
"}\n"
"QDockWidget::float-button,QDockWidget::close-button\n"
" {\n"
"    border: 1px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    width: 20px; \n"
"    subcontrol-position: center right;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"    top: 8px; \n"
"    left: 0px; \n"
"    bottom: 0px;\n"
"    right:14px;\n"
"}\n"
"\n"
"QDockWidget::float-button:hover {\n"
"  background-color: rgb(57, 65, 80);\n"
"  border: 1px solid rgb(61, 70, 86);\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QDockWidget::close-button:hover {\n"
"  background-color: rgb(57, 65, 80);\n"
"  border: 1px solid rgb(61, 70, 86);\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QDockWidget::float-button:pressed {\n"
"  background-color: rgb(35, 40, 49);\n"
"  border: 1px solid rgb(43, 50, 61);\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed {\n"
"  background-color: rgb(35, 40, 49);\n"
"  border: 1px solid rgb(43, 50, 61);\n"
"  border-radius: 5px;\n"
"}\n"
"QDockWidget::float-button:disabled,\n"
"QDockWidget::close-button:disabled {\n"
"    border: 1px solid rgb(43, 50, 61);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(43, 50, 61);\n"
"}\n"
"QDockWidget:disabled {\n"
"    color:rgb(120,120,120);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"    background-color: rgb(43, 50, 61);\n"
"}\n"
"\n"
"/*  QScrollBar  */\n"
"QScrollBar:horizontal {\n"
"  border: 1px solid  rgb(23, 27, 33);\n"
"  border-radius: 5px;\n"
"  background-color: rgb(23, 27, 33);\n"
"  height: 12px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"  border: 1px solid  rgb(23, 27, 33);\n"
"  border-radius: 5px;\n"
"  background-color: rgb(23, 27, 33);\n"
"  width: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
"  border: 1 solid  rgb(71, 128, 180);\n"
"  border-radius: 5px;\n"
"  background-color: rgb(71, 128, 180);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"  min-width: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"  min-height: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover,\n"
"QScrollBar::handle:horizontal:hover {\n"
"  background-color: rgb(111, 168, 220);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"  border: 0;\n"
"  background: transparent;\n"
"  width: 0px;\n"
"  height: 0px;\n"
"}\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:vertical,\n"
"QScrollBar::sub-page:horizontal\n"
"{\n"
"    background:transparent;\n"
"}\n"
"\n"
"/*  QSlider  */\n"
"QSlider:horizontal {\n"
"  min-height: 24px;\n"
"  max-height: 24px;\n"
"}\n"
"\n"
"QSlider:vertical {\n"
"  min-width: 24px;\n"
"  max-width: 24px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"  height: 4px;\n"
"  background: rgb(33, 37, 43);\n"
"  margin: 0 10px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"  width: 4px;\n"
"  background: rgb(33, 37, 43);\n"
"  border-radius: 24px;\n"
"  margin: 10px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"  image: url(:/icons/images/icons/circle.svg);\n"
"  width: 20px;\n"
"  height: 20px;\n"
"  margin: -20px -10px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"  image: url(:/icons/images/icons/circle.svg);\n"
"  border-radius: 20px;\n"
"  width: 20px;\n"
"  height: 20px;\n"
"  margin: -10px -20px;\n"
"}\n"
"\n"
"QSlider::add-page {\n"
"background: rgb(33, 37, 43);\n"
"}\n"
"\n"
"QSlider::sub-page {\n"
"background: rgb(111, 168, 220);\n"
"}\n"
"\n"
"/*  Spin buttons  */\n"
"QDateTimeEdit,\n"
"QDoubleSpinBox,\n"
"QSpinBox {\n"
"     background-color: rgb(33, 37, 43);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(111, 168, 220);\n"
"}\n"
"QDateTimeEdit:hover,\n"
"QDoubleSpinBox:hover,\n"
"QSpinBox:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QDateTimeEdit:focus,\n"
"QDoubleSpinBox:focus,\n"
"QSpinBox:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"QDateTimeEdit:disabled,\n"
"QDoubleSpinBox:disabled,\n"
"QSpinBox:disabled {\n"
"     color:rgb(120,120,120);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"    background-color: rgb(43, 50, 61);\n"
"}\n"
"\n"
"QDateTimeEdit::up-button,\n"
"QDoubleSpinBox::up-button,\n"
"QSpinBox::up-button {\n"
"  subcontrol-origin: border;\n"
"  subcontrol-position: top right;\n"
"  width: 20px;\n"
"  image: url(:/icons/images/icons/cil-arrow-top.png);\n"
"  border-width: 0px;\n"
"  margin-right: 5px;\n"
"  margin-top: 5px;\n"
"}\n"
"\n"
"QDateTimeEdit::up-button:disabled,\n"
"QDoubleSpinBox::up-button:disabled,\n"
"QSpinBox::up-button:disabled {\n"
"     image: url(:/icons/images/icons/cil-arrow-top.png);\n"
"     color:rgb(120,120,120);\n"
"}\n"
"\n"
"QDateTimeEdit::down-button,\n"
"QDoubleSpinBox::down-button,\n"
"QSpinBox::down-button {\n"
"  subcontrol-origin: border;\n"
"  subcontrol-position: bottom right;\n"
"  width: 20px;\n"
"  image: url(:/icons/images/icons/cil-arrow-bottom.png);\n"
"  border-width: 0px;\n"
"  border-top-width: 0;\n"
"  margin-right: 5px;\n"
"  margin-bottom: 5px;\n"
"}\n"
"\n"
"QDateTimeEdit::down-button:disabled,\n"
"QDoubleSpinBox::down-button:disabled,\n"
"QSpinBox::down-button:disabled {\n"
"  image: url(:/icons/images/icons/cil-arrow-bottom.png);\n"
"}\n"
"\n"
"/*  QComboBox  */\n"
"QComboBox {\n"
"  color:  rgb(221, 221, 221);\n"
"  background-color: rgb(33, 37, 43);\n"
"  border-radius: 5px;\n"
"  border: 2px solid rgb(33, 37, 43);\n"
"  selection-color: rgb(255, 255, 255);\n"
"  selection-background-color: rgb(111, 168, 220);\n"
"  border-top-left-radius: 4px;\n"
"  border-top-right-radius: 4px;\n"
"  padding-left: 10px;\n"
"  height: 30px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"QComboBox:disabled {\n"
"  color:rgb(120,120,120);\n"
"  border: 2px solid rgb(43, 50, 61);\n"
"  background-color: rgb(43, 50, 61);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"  border: none;\n"
"  width: 20px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"  image: url(:/icons/images/icons/cil-arrow-bottom.png);\n"
"  margin-right: 12px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  background-color: rgb(33, 37, 43);\n"
"  border: 2px solid rgb(64, 71, 88);\n"
"  border-radius: 0px;\n"
"}\n"
"QComboBox::indicator:checked {\n"
"  image: url(:/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"\n"
"QComboBox::item {\n"
"  height: 25px;\n"
"  border: 5px solid transparent;\n"
"  padding-left:0px;\n"
"  color:rgb(221, 221, 221);\n"
"}\n"
"QComboBox::item:selected {\n"
"  color:  rgb(221, 221, 221);\n"
"  background-color: rgb(111, 168, 220);\n"
"  border-radius: 0px;\n"
"}\n"
"\n"
"/*Label*/\n"
"QLabel {\n"
"    color: rgb(221, 221, 221);\n"
"    padding-left: 5px;\n"
"    padding-right: 2px;\n"
"    border-radius: 5px;    \n"
"    background-color: transparent;\n"
"}\n"
"QLabel:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);;\n"
"}\n"
"QLabel:disabled {\n"
"    color:rgb(120,120,120);\n"
"    background-color: transparent;\n"
"}\n"
"/*Button */\n"
"QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"QPushButton:disabled {\n"
"    color:rgb(120,120,120);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(43, 50, 61);\n"
"}\n"
"\n"
"/*LineEdit */\n"
"QLineEdit {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(111, 168, 220);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"QLineEdit:disabled {\n"
"    color:rgb(120,120,120);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"    background-color: rgb(43, 50, 61);\n"
"}\n"
"/* RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"QRadioButton:disabled {\n"
"    color:rgb(120,120,120);\n"
"    border: 3px solid rgb(43, 50, 61);\n"
"    background-color: rgb(43, 50, 61);\n"
"}\n"
"/*CheckBox */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"QCheckBox:disabled {\n"
"    color:rgb(120,120,120);\n"
"    border: 3px solid rgb(43, 50, 61);\n"
"    background-color: rgb(43, 50, 61);\n"
"}\n"
"/*  QTabBar  */\n"
"QTabWidget{\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"QTabBar{\n"
"  text-transform: uppercase;\n"
"  font-weight: bold;\n"
"  background-color: rgb(40, 44, 52);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"  max-width:150px;\n"
"  min-width:150px;\n"
"  max-height:30px;\n"
"  min-height:30px;\n"
"  border:0px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom,QTabBar::tab:top{\n"
"  padding: 3px;\n"
"  height: 30px;\n"
"}\n"
"\n"
"QTabBar::tab:left,QTabBar::tab:right{\n"
"  padding: 3px;\n"
"  width: 30px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected,\n"
"QTabBar::tab:top:hover {\n"
"  color: rgb(109, 158, 235);\n"
"  border-bottom: 3px solid rgb(109, 158, 235);\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected,\n"
"QTabBar::tab:bottom:hover {\n"
"  padding: 0px;\n"
"  color:rgb(109, 158, 235);\n"
"  border-top: 3px solid rgb(109, 158, 235);\n"
"}\n"
"\n"
"QTabBar::tab:right:selected,\n"
"QTabBar::tab:right:hover {\n"
"  color: rgb(109, 158, 235);\n"
"  border-left: 3px solid rgb(109, 158, 235);\n"
"}\n"
"\n"
"QTabBar::tab:left:selected,\n"
"QTabBar::tab:left:hover {\n"
"  color: rgb(109, 158, 235);\n"
"  border-right: 3px solid rgb(109, 158, 235);\n"
"}\n"
"\n"
"QTabBar::close-button {\n"
"  image: url(:/icons/images/icons/close.svg);\n"
"  background-color:  rgb(40, 44, 52);\n"
"  border-radius: 10px; \n"
"}\n"
"\n"
"QTabBar::close-button:hover {\n"
"    background-color: rgb(253, 84, 63);\n"
"}\n"
"QTabBar::close-button:pressed {\n"
"    background-color: rgb(196, 58, 43);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tab = QtWidgets.QTabWidget(self.centralwidget)
        self.tab.setStyleSheet("QTableView {\n"
"  font: 10t \"HarmonyOS Sans SC\";\n"
"  background-color: rgb(40, 44, 52);\n"
"  border: 1px solid rgb(64, 71, 88);\n"
"  border-radius: 4px;\n"
"  selection-background-color: rgb(71, 128, 180);\n"
"  /*两行交替的颜色，第二行*/\n"
"  alternate-background-color: rgb(43, 47, 53);\n"
"}\n"
"\n"
"QTableView:focus {\n"
"  selection-background-color: rgb(111, 168, 220);\n"
"}\n"
"\n"
"QTableView::item {\n"
"  font: 8t \"HarmonyOS Sans SC\";\n"
"  padding: 0px;\n"
"  min-height: 32px;\n"
"  color: rgb(221, 221, 221);\n"
"  selection-color: rgb(221, 221, 221); /* For Windows */\n"
"}\n"
"/*  Items Selection */\n"
"QTableView::item:selected {\n"
"  background-color: rgb(71, 128, 180);\n"
"  selection-background-color: rgb(71, 128, 180);\n"
"  color:rgb(221, 221, 221);\n"
"  selection-color:rgb(221, 221, 221); /* For Windows */\n"
"}\n"
"\n"
"QTableView::item:selected:focus {\n"
"  background-color: rgb(111, 168, 220);\n"
"  selection-background-color: rgb(111, 168, 220);\n"
"  color: rgb(255, 255, 255);\n"
"  selection-color: rgb(255, 255, 255); /* For Windows */\n"
"}\n"
"QTableView::item:disabled {\n"
"  color: rgb(120,120,120);\n"
"  selection-color: rgb(120,120,120);\n"
"  background-color: rgb(43, 50, 61);\n"
"  selection-background-color: rgb(43, 50, 61);\n"
"}\n"
"/*  QTableView  */\n"
"\n"
"QTableCornerButton::section {\n"
"  background-color: rgb(33, 37, 43);\n"
"  border-radius: 2px;\n"
"  border-right: 1px solid;\n"
"  border-bottom: 1px solid;\n"
"  border-color: rgb(64, 71, 88);\n"
"}\n"
"QTableCornerButton::section:disabled {\n"
"  background-color:  rgb(43, 50, 61);\n"
"  border-radius: 2px;\n"
"  border-right: 1px solid;\n"
"  border-bottom: 1px solid;\n"
"  border-color: rgb(64, 71, 88);\n"
"}\n"
"\n"
"QHeaderView {\n"
"  border: none;\n"
"}\n"
"\n"
"QHeaderView::section:disabled {\n"
"  color: rgb(120, 120, 120);\n"
"  text-transform: uppercase;\n"
"  background-color: rgb(43, 50, 61);\n"
"  border-radius: 2px;\n"
"  border-right: 1px solid;\n"
"  border-bottom: 1px solid;\n"
"  border-color:rgb(64, 71, 88);\n"
"}\n"
"QHeaderView::section {\n"
"  color: rgb(221, 221, 221);\n"
"  text-transform: uppercase;\n"
"  background-color: rgb(33, 37, 43);\n"
"  border-radius: 2px;\n"
"  border-right: 1px solid;\n"
"  border-bottom: 1px solid;\n"
"  border-color:rgb(64, 71, 88);\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"  padding: 10 0 10 0;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"  padding: 0 10 0 10;\n"
"}\n"
"QTableView QLineEdit {\n"
"  color: rgb(221, 221, 221);\n"
"  background-color: rgb(33, 37, 43);\n"
"  border: 1px solid rgb(111, 168, 220);\n"
"  border-radius: unset;\n"
"  padding: unset;\n"
"  padding-left: unset;\n"
"  height: unset;\n"
"  border-width: unset;\n"
"  border-top-left-radius: unset;\n"
"  border-top-right-radius: unset;\n"
"}\n"
"QTableView QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QTableView QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.tab.setObjectName("tab")
        self.last = QtWidgets.QWidget()
        self.last.setObjectName("last")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.last)
        self.gridLayout_3.setContentsMargins(-1, 15, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.web = QtWebEngineWidgets.QWebEngineView(self.last)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.web.sizePolicy().hasHeightForWidth())
        self.web.setSizePolicy(sizePolicy)
        self.web.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.web.setObjectName("web")
        self.gridLayout_3.addWidget(self.web, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backward = QtWidgets.QPushButton(self.last)
        self.backward.setMinimumSize(QtCore.QSize(25, 25))
        self.backward.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.backward.setFont(font)
        self.backward.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backward.setIcon(icon)
        self.backward.setIconSize(QtCore.QSize(20, 20))
        self.backward.setFlat(False)
        self.backward.setObjectName("backward")
        self.horizontalLayout_2.addWidget(self.backward)
        self.forward = QtWidgets.QPushButton(self.last)
        self.forward.setMinimumSize(QtCore.QSize(25, 25))
        self.forward.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.forward.setFont(font)
        self.forward.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forward.setIcon(icon1)
        self.forward.setIconSize(QtCore.QSize(20, 20))
        self.forward.setFlat(False)
        self.forward.setObjectName("forward")
        self.horizontalLayout_2.addWidget(self.forward)
        self.refresh = QtWidgets.QPushButton(self.last)
        self.refresh.setMinimumSize(QtCore.QSize(25, 25))
        self.refresh.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.refresh.setFont(font)
        self.refresh.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh.setIcon(icon2)
        self.refresh.setIconSize(QtCore.QSize(14, 14))
        self.refresh.setFlat(False)
        self.refresh.setObjectName("refresh")
        self.horizontalLayout_2.addWidget(self.refresh)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.tab.addTab(self.last, "")
        self.verticalLayout_4.addWidget(self.tab)
        MainWindow.setCentralWidget(self.centralwidget)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(210, 740))
        self.dockWidget.setMaximumSize(QtCore.QSize(350, 524287))
        self.dockWidget.setStyleSheet("")
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setMinimumSize(QtCore.QSize(0, 600))
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 600))
        self.widget.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.widget.setFont(font)
        self.widget.setMouseTracking(False)
        self.widget.setAutoFillBackground(False)
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.demo = QtWidgets.QCheckBox(self.widget)
        self.demo.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.demo.setFont(font)
        self.demo.setObjectName("demo")
        self.verticalLayout_20.addWidget(self.demo)
        self.console = QtWidgets.QCheckBox(self.widget)
        self.console.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.console.setFont(font)
        self.console.setObjectName("console")
        self.verticalLayout_20.addWidget(self.console)
        self.report = QtWidgets.QCheckBox(self.widget)
        self.report.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.report.setFont(font)
        self.report.setChecked(True)
        self.report.setObjectName("report")
        self.verticalLayout_20.addWidget(self.report)
        self.head = QtWidgets.QCheckBox(self.widget)
        self.head.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.head.setFont(font)
        self.head.setObjectName("head")
        self.verticalLayout_20.addWidget(self.head)
        self.max = QtWidgets.QCheckBox(self.widget)
        self.max.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.max.setFont(font)
        self.max.setObjectName("max")
        self.verticalLayout_20.addWidget(self.max)
        self.screenshot = QtWidgets.QCheckBox(self.widget)
        self.screenshot.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.screenshot.setFont(font)
        self.screenshot.setObjectName("screenshot")
        self.verticalLayout_20.addWidget(self.screenshot)
        self.rs = QtWidgets.QCheckBox(self.widget)
        self.rs.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.rs.setFont(font)
        self.rs.setChecked(True)
        self.rs.setObjectName("rs")
        self.verticalLayout_20.addWidget(self.rs)
        self.first_stop = QtWidgets.QCheckBox(self.widget)
        self.first_stop.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.first_stop.setFont(font)
        self.first_stop.setChecked(False)
        self.first_stop.setObjectName("first_stop")
        self.verticalLayout_20.addWidget(self.first_stop)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.thread_num = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thread_num.sizePolicy().hasHeightForWidth())
        self.thread_num.setSizePolicy(sizePolicy)
        self.thread_num.setMinimumSize(QtCore.QSize(0, 28))
        self.thread_num.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.thread_num.setFont(font)
        self.thread_num.setMaximum(10)
        self.thread_num.setProperty("value", 1)
        self.thread_num.setObjectName("thread_num")
        self.horizontalLayout_7.addWidget(self.thread_num)
        self.verticalLayout_20.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.demo_sleep = QtWidgets.QSpinBox(self.widget)
        self.demo_sleep.setMinimumSize(QtCore.QSize(0, 28))
        self.demo_sleep.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.demo_sleep.setFont(font)
        self.demo_sleep.setMaximum(10)
        self.demo_sleep.setProperty("value", 1)
        self.demo_sleep.setObjectName("demo_sleep")
        self.horizontalLayout_8.addWidget(self.demo_sleep)
        self.verticalLayout_20.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.highlights = QtWidgets.QSpinBox(self.widget)
        self.highlights.setMinimumSize(QtCore.QSize(0, 28))
        self.highlights.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.highlights.setFont(font)
        self.highlights.setMaximum(10)
        self.highlights.setProperty("value", 3)
        self.highlights.setObjectName("highlights")
        self.horizontalLayout_10.addWidget(self.highlights)
        self.verticalLayout_20.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_13.addWidget(self.label_4)
        self.browser = QtWidgets.QComboBox(self.widget)
        self.browser.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.browser.setFont(font)
        self.browser.setObjectName("browser")
        self.browser.addItem("")
        self.browser.addItem("")
        self.browser.addItem("")
        self.browser.addItem("")
        self.horizontalLayout_13.addWidget(self.browser)
        self.verticalLayout_20.addLayout(self.horizontalLayout_13)
        self.save = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save.sizePolicy().hasHeightForWidth())
        self.save.setSizePolicy(sizePolicy)
        self.save.setMinimumSize(QtCore.QSize(30, 0))
        self.save.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.save.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon3)
        self.save.setIconSize(QtCore.QSize(14, 14))
        self.save.setObjectName("save")
        self.verticalLayout_20.addWidget(self.save)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_14.addWidget(self.label_8)
        self.driver = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.driver.sizePolicy().hasHeightForWidth())
        self.driver.setSizePolicy(sizePolicy)
        self.driver.setMinimumSize(QtCore.QSize(0, 28))
        self.driver.setMaximumSize(QtCore.QSize(16777215, 28))
        self.driver.setObjectName("driver")
        self.horizontalLayout_14.addWidget(self.driver)
        self.verticalLayout_20.addLayout(self.horizontalLayout_14)
        self.install = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.install.sizePolicy().hasHeightForWidth())
        self.install.setSizePolicy(sizePolicy)
        self.install.setMinimumSize(QtCore.QSize(0, 28))
        self.install.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.install.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-cloud-download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.install.setIcon(icon4)
        self.install.setIconSize(QtCore.QSize(14, 14))
        self.install.setObjectName("install")
        self.verticalLayout_20.addWidget(self.install)
        self.horizontalLayout_6.addLayout(self.verticalLayout_20)
        self.verticalLayout_3.addWidget(self.widget)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockWidget_4 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_4.setMinimumSize(QtCore.QSize(297, 200))
        self.dockWidget_4.setStyleSheet("\n"
"")
        self.dockWidget_4.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_4.setObjectName("dockWidget_4")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setMinimumSize(QtCore.QSize(0, 120))
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_2.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 30))
        self.label_2.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_15.addWidget(self.label_2)
        self.config_path = QtWidgets.QLineEdit(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_path.sizePolicy().hasHeightForWidth())
        self.config_path.setSizePolicy(sizePolicy)
        self.config_path.setMinimumSize(QtCore.QSize(0, 30))
        self.config_path.setMaximumSize(QtCore.QSize(16777215, 30))
        self.config_path.setObjectName("config_path")
        self.horizontalLayout_15.addWidget(self.config_path)
        self.select_config = QtWidgets.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_config.sizePolicy().hasHeightForWidth())
        self.select_config.setSizePolicy(sizePolicy)
        self.select_config.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.select_config.setFont(font)
        self.select_config.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.select_config.setStyleSheet("background-color: rgb(52, 59, 72);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.select_config.setIcon(icon5)
        self.select_config.setObjectName("select_config")
        self.horizontalLayout_15.addWidget(self.select_config)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 30))
        self.label_3.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_16.addWidget(self.label_3)
        self.data_path = QtWidgets.QLineEdit(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_path.sizePolicy().hasHeightForWidth())
        self.data_path.setSizePolicy(sizePolicy)
        self.data_path.setMinimumSize(QtCore.QSize(0, 30))
        self.data_path.setMaximumSize(QtCore.QSize(16777215, 30))
        self.data_path.setObjectName("data_path")
        self.horizontalLayout_16.addWidget(self.data_path)
        self.select_data = QtWidgets.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_data.sizePolicy().hasHeightForWidth())
        self.select_data.setSizePolicy(sizePolicy)
        self.select_data.setMinimumSize(QtCore.QSize(100, 30))
        self.select_data.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.select_data.setFont(font)
        self.select_data.setIcon(icon5)
        self.select_data.setObjectName("select_data")
        self.horizontalLayout_16.addWidget(self.select_data)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.run = QtWidgets.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run.sizePolicy().hasHeightForWidth())
        self.run.setSizePolicy(sizePolicy)
        self.run.setMinimumSize(QtCore.QSize(0, 30))
        self.run.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.run.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-media-play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run.setIcon(icon6)
        self.run.setIconSize(QtCore.QSize(14, 14))
        self.run.setObjectName("run")
        self.horizontalLayout_17.addWidget(self.run)
        self.stop = QtWidgets.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop.sizePolicy().hasHeightForWidth())
        self.stop.setSizePolicy(sizePolicy)
        self.stop.setMinimumSize(QtCore.QSize(0, 30))
        self.stop.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans SC")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.stop.setFont(font)
        self.stop.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-media-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon7)
        self.stop.setIconSize(QtCore.QSize(14, 14))
        self.stop.setObjectName("stop")
        self.horizontalLayout_17.addWidget(self.stop)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.dockWidget_4.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_4)

        self.retranslateUi(MainWindow)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backward.setToolTip(_translate("MainWindow", "后退"))
        self.forward.setToolTip(_translate("MainWindow", "前进"))
        self.refresh.setToolTip(_translate("MainWindow", "刷新"))
        self.tab.setTabText(self.tab.indexOf(self.last), _translate("MainWindow", "运行结果"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "设置"))
        self.demo.setText(_translate("MainWindow", "演示"))
        self.console.setText(_translate("MainWindow", "控制台"))
        self.report.setText(_translate("MainWindow", "报告"))
        self.head.setText(_translate("MainWindow", "后台执行"))
        self.max.setText(_translate("MainWindow", "最大化网页窗口"))
        self.screenshot.setText(_translate("MainWindow", "保存最后页面截图"))
        self.rs.setText(_translate("MainWindow", "重用会话框"))
        self.first_stop.setText(_translate("MainWindow", "遇错即停"))
        self.label_6.setText(_translate("MainWindow", "线程数目"))
        self.label_5.setText(_translate("MainWindow", "演示间隔(秒)"))
        self.label_7.setText(_translate("MainWindow", "演示闪烁次数"))
        self.label_4.setText(_translate("MainWindow", "浏览器"))
        self.browser.setItemText(0, _translate("MainWindow", "谷歌"))
        self.browser.setItemText(1, _translate("MainWindow", "火狐"))
        self.browser.setItemText(2, _translate("MainWindow", "edge"))
        self.browser.setItemText(3, _translate("MainWindow", "ie"))
        self.save.setText(_translate("MainWindow", "保存"))
        self.label_8.setText(_translate("MainWindow", "驱动版本"))
        self.install.setText(_translate("MainWindow", "下载驱动"))
        self.dockWidget_4.setWindowTitle(_translate("MainWindow", "运行"))
        self.label_2.setText(_translate("MainWindow", "配置文件路径"))
        self.select_config.setText(_translate("MainWindow", "选择文件"))
        self.label_3.setText(_translate("MainWindow", "数据文件路径"))
        self.select_data.setText(_translate("MainWindow", "选择文件"))
        self.run.setText(_translate("MainWindow", "运行"))
        self.stop.setText(_translate("MainWindow", "暂停"))
from PyQt5 import QtWebEngineWidgets
import lib.resources_rc
